const monstera =
  'https://images.pexels.com/photos/3125195/pexels-photo-3125195.jpeg';

export const plantList = [
  {
    name: 'monstera',
    category: 'classique',
    id: '1ed',
    light: 2,
    water: 3,
    cover: monstera,
    price: 15,
  },
  {
    name: 'ficus lyrata',
    category: 'classique',
    id: '2ab',
    isBestSale: true,
    light: 2,
    water: 3,
    cover: monstera,
    price: 15,
  },
  {
    name: 'pothos argenté',
    category: 'classique',
    id: '3sd',
    isSpecialOffer: true,
    light: 2,
    water: 3,
    cover: monstera,
    price: 15,
  },
  {
    name: 'yucca',
    category: 'classique',
    id: '4kk',
    light: 2,
    water: 3,
    cover: monstera,
    price: 15,
  },
  {
    name: 'olivier',
    category: 'extérieur',
    id: '5pl',
    isAvailable: false,
    light: 2,
    water: 3,
    cover: monstera,
    price: 15,
  },
  {
    name: 'géranium',
    category: 'extérieur',
    id: '6uo',
    light: 2,
    water: 3,
    cover: monstera,
    price: 15,
  },
  {
    name: 'basilique',
    category: 'extérieur',
    id: '7ie',
    isSpecialOffer: true,
    light: 2,
    water: 3,
    cover: monstera,
    price: 15,
  },
  {
    name: 'aloe',
    category: 'plante grasse',
    id: '8fp',
    isSpecialOffer: true,
    light: 2,
    water: 3,
    cover: monstera,
    price: 15,
  },
  {
    name: 'succulente',
    category: 'plante grasse',
    id: '9vn',
    light: 2,
    water: 3,
    cover: monstera,
    price: 15,
  },
];
